dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0  # یہ version change کریں
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.14
  google_fonts: ^6.1.0  # یہ رہنے دیں
  intl: ^0.18.1
